"use strict";


// Uso la API de SoundCloud para mediante un embed de iframes poder reproducir las canciones de la playlist.


document.addEventListener("DOMContentLoaded", function () {
  initializePlaylistItems();
});

function initializePlaylistItems() {
  const cards = document.querySelectorAll(".playlist-item");
  let lastClickedIcon = null; 

  cards.forEach((card) => { // Añado eventos de clic a cada elemento de la lista de reproducción.
    card.addEventListener("click", function () {
      handleCardClick(card, lastClickedIcon);
    });
  });

  function handleCardClick(card, lastClickedIcon) { // Maneja el clic en un elemento de la lista de reproducción.
  
    if (lastClickedIcon) {
      lastClickedIcon.style.display = "none"; // Oculta el icono de reproducción del último elemento clicado.
    }

   
    let playIcon = addOrShowPlayIcon(card); // llamo a la función para añadir o mostrar el icono de reproducción.
   
    updateSoundCloudPlayer(card); // llamo a la función para actualizar el reproductor de SoundCloud.

   
    lastClickedIcon = playIcon;
  }

  function addOrShowPlayIcon(card) { // Añade o muestra el icono de reproducción.
    let playIcon = card.querySelector(".fa-play");
    if (!playIcon) {
      playIcon = document.createElement("i");
      playIcon.className = "fa fa-play"; // Añado clase al icono y defino su estilo.
      playIcon.style.position = "absolute";
      playIcon.style.top = "10px";
      playIcon.style.left = "10px";
      playIcon.style.color = "#00BFFF";
      card.appendChild(playIcon);
    } else {
      playIcon.style.display = "block";
    }
    return playIcon;
  }

  function updateSoundCloudPlayer(card) { // Actualiza el reproductor de SoundCloud.
    const trackId = card.getAttribute("data-track-id");
    const iframeHTML = getIframeHTMLByTrackId(trackId);
    document.getElementById("soundCloudPlayer").innerHTML = iframeHTML;
  }
}

function getIframeHTMLByTrackId(trackId) { // Devuelve el iframe de SoundCloud para la canción seleccionada.s
  const iframes = {
 
    track1: `<iframe width="100%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/1669013580&color=%2300bfff&auto_play=true&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/des-608783297" title="JPEGVIC" target="_blank" style="color: #cccccc; text-decoration: none;">JPEGVIC</a> · <a href="https://soundcloud.com/des-608783297/portrait-eya" title="Portrait - JPEGVIC" target="_blank" style="color: #cccccc; text-decoration: none;">Portrait - JPEGVIC</a></div>`,
    track2: `<iframe width="100%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/1652853270&color=%2300bfff&auto_play=true&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/martavius-j-leonard" title="Tae Leon" target="_blank" style="color: #cccccc; text-decoration: none;">Tae Leon</a> · <a href="https://soundcloud.com/martavius-j-leonard/bag-drop-r-b-mashup" title="Bag Drop (R&amp;B Mashup)" target="_blank" style="color: #cccccc; text-decoration: none;">Bag Drop (R&amp;B Mashup)</a></div>`,
    track3: `<iframe width="100%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/1649748606&color=%2300bfff&auto_play=true&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/shannonleanne070113" title="Essell&#x27;Tee" target="_blank" style="color: #cccccc; text-decoration: none;">Essell&#x27;Tee</a> · <a href="https://soundcloud.com/shannonleanne070113/simping-for-your-love-original-by-shannon-t" title="Simping For Your Love| Shan T | (Prod. by JustBen Beats)." target="_blank" style="color: #cccccc; text-decoration: none;">Simping For Your Love| Shan T | (Prod. by JustBen Beats).</a></div>`,
    track4: `<iframe width="100%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/1689587520&color=%2300bfff&auto_play=true&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/jordan-jones-95012967" title="Jojochi" target="_blank" style="color: #cccccc; text-decoration: none;">Jojochi</a> · <a href="https://soundcloud.com/jordan-jones-95012967/timeline" title="Timeline" target="_blank" style="color: #cccccc; text-decoration: none;">Timeline</a></div>`,
    track5: `<iframe width="100%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/1627409547&color=%2300bfff&auto_play=true&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/i-me-mine" title="I Me Mine" target="_blank" style="color: #cccccc; text-decoration: none;">I Me Mine</a> · <a href="https://soundcloud.com/i-me-mine/harmonizer" title="Harmonizer" target="_blank" style="color: #cccccc; text-decoration: none;">Harmonizer</a></div>`,
    track6: `<iframe width="100%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/1690210155&color=%2300bfff&auto_play=true&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/scc-scmusic" title="SCC" target="_blank" style="color: #cccccc; text-decoration: none;">SCC</a> · <a href="https://soundcloud.com/scc-scmusic/ungkapan-cinta" title="Ungkapan Cinta" target="_blank" style="color: #cccccc; text-decoration: none;">Ungkapan Cinta</a></div>`,
    track7: `<iframe width="100%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/1679540622&color=%2300bfff&auto_play=true&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/jim-gear" title="Jim Gear" target="_blank" style="color: #cccccc; text-decoration: none;">Jim Gear</a> · <a href="https://soundcloud.com/jim-gear/knockin-on-heavens-door" title="Knockin On Heavens Door" target="_blank" style="color: #cccccc; text-decoration: none;">Knockin On Heavens Door</a></div>`,
    track8: `<iframe width="100%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/1623284163&color=%2300bfff&auto_play=true&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/whtrbbtobj" title="wht.rbbt.obj" target="_blank" style="color: #cccccc; text-decoration: none;">wht.rbbt.obj</a> · <a href="https://soundcloud.com/whtrbbtobj/love-on-hold" title="Love On Hold" target="_blank" style="color: #cccccc; text-decoration: none;">Love On Hold</a></div>`,
    track9: `<iframe width="100%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/1727229990&color=%2300bfff&auto_play=true&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/sughn" title="sughn" target="_blank" style="color: #cccccc; text-decoration: none;">sughn</a> · <a href="https://soundcloud.com/sughn/safe-space" title="safe space" target="_blank" style="color: #cccccc; text-decoration: none;">safe space</a></div>`,
    track10: `<iframe width="100%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/1747126113&color=%2300bfff&auto_play=true&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/micky47237" title="Micky" target="_blank" style="color: #cccccc; text-decoration: none;">Micky</a> · <a href="https://soundcloud.com/micky47237/something-in-the-orange" title="Something In The Orange" target="_blank" style="color: #cccccc; text-decoration: none;">Something In The Orange</a></div>`,
    track11: `<iframe width="100%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/1409266825&color=%2300bfff&auto_play=true&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/vendettawrld_309" title="𝖗𝖊𝐯𝖊𝖓𝖌𝖊𝐰𝖗𝖑𝐝 ♪" target="_blank" style="color: #cccccc; text-decoration: none;">𝖗𝖊𝐯𝖊𝖓𝖌𝖊𝐰𝖗𝖑𝐝 ♪</a> · <a href="https://soundcloud.com/vendettawrld_309/late-night-juice-wrld-i-wonder-juice-wrld-adore-you-juice-wrld-zoom-juice-wrld-999-lljw" title="LATE NIGHT • I WONDER • ADORE YOU • ZOOM • Juice WRLD" target="_blank" style="color: #cccccc; text-decoration: none;">LATE NIGHT • I WONDER • ADORE YOU • ZOOM • Juice WRLD</a></div>`,
    track12: `<iframe width="100%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/1722330843&color=%2300bfff&auto_play=true&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/marik_yt" title="Tomioka" target="_blank" style="color: #cccccc; text-decoration: none;">Tomioka</a> · <a href="https://soundcloud.com/marik_yt/shaya-zamora-cigarette" title="Shaya Zamora - Cigarette" target="_blank" style="color: #cccccc; text-decoration: none;">Shaya Zamora - Cigarette</a></div>`,
    track13: `<iframe width="100%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/playlists/1734885096&color=%2300bfff&auto_play=true&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/trending-music-ibe" title="Trending Music" target="_blank" style="color: #cccccc; text-decoration: none;">Trending Music</a> · <a href="https://soundcloud.com/trending-music-ibe/sets/electronic" title="Electronic" target="_blank" style="color: #cccccc; text-decoration: none;">Electronic</a></div>`,
    track14: `<iframe width="100%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/playlists/1734885096&color=%2300bfff&auto_play=true&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/trending-music-ibe" title="Trending Music" target="_blank" style="color: #cccccc; text-decoration: none;">Trending Music</a> · <a href="https://soundcloud.com/trending-music-ibe/sets/electronic" title="Electronic" target="_blank" style="color: #cccccc; text-decoration: none;">Electronic</a></div>`,
    track15: `<iframe width="100%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/1738534452&color=%2300bfff&auto_play=true&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/hmwl" title="House Music With Love (HMWL)" target="_blank" style="color: #cccccc; text-decoration: none;">House Music With Love (HMWL)</a> · <a href="https://soundcloud.com/hmwl/tomi-h-soul-star-nnangalimbe-extended-mix" title="Tomi H &amp; Soul Star - Nnangalimbe (Extended Mix) - Out 9 Feb" target="_blank" style="color: #cccccc; text-decoration: none;">Tomi H &amp; Soul Star - Nnangalimbe (Extended Mix - Out 9 Feb</a></div>`,
    track16: `<iframe width="100%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/1749910413&color=%2300bfff&auto_play=true&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/webton-music" title="WEBTON" target="_blank" style="color: #cccccc; text-decoration: none;">WEBTON</a> · <a href="https://soundcloud.com/webton-music/guarana" title="GUARANA" target="_blank" style="color: #cccccc; text-decoration: none;">GUARANA</a></div>`,
   
  };
  return iframes[trackId] || "Por favor seleciona una cación para reproducir."; 
}
